Add organizations servlet
googleinterns/step130-2020 pull request #3
Opened 2020-06-26 19:33 UTC by andrewm898

adds a servlet and HTML page to handle adding new organizations to the datastore

2020-06-26 19:38 UTC, andrewm898 commented
@googlebot I signed it!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: googlebot <notifications@github.com>
Sent: Friday, June 26, 2020 3:33:20 PM
To: googleinterns/step130-2020 <step130-2020@noreply.github.com>
Cc: Masek, Andrew James <amasek@purdue.edu>; Author <author@noreply.github.com>
Subject: Re: [googleinterns/step130-2020] Add organizations servlet (#3)


Thanks for your pull request. It looks like this may be your first contribution to a Google open source project (if not, look below for help). Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).

📝 Please visit https://cla.developers.google.com/ to sign.

Once you've signed (or fixed any issues), please reply here with @googlebot I signed it! and we'll verify it.

________________________________
What to do if you already signed the CLA
Individual signers

  *   It's possible we don't have your GitHub username or you're using a different email address on your commit. Check your existing CLA data<https://cla.developers.google.com/clas> and verify that your email is set on your git commits<https://help.github.com/articles/setting-your-email-in-git/>.

Corporate signers

  *   Your company has a Point of Contact who decides which employees are authorized to participate. Ask your POC to be added to the group of authorized contributors. If you don't know who your Point of Contact is, direct the Google project maintainer to go/cla#troubleshoot<http://go/cla#troubleshoot> (Public version<https://opensource.google/docs/cla/#troubleshoot>).
  *   The email used to register you as an authorized contributor must be the email used for the Git commit. Check your existing CLA data<https://cla.developers.google.com/clas> and verify that your email is set on your git commits<https://help.github.com/articles/setting-your-email-in-git/>.
  *   The email used to register you as an authorized contributor must also be attached to your GitHub account<https://github.com/settings/emails>.

ℹ️ Googlers: Go here<https://goto.google.com/prinfo/https%3A%2F%2Fgithub.com%2Fgoogleinterns%2Fstep130-2020%2Fpull%2F3> for more info.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/googleinterns/step130-2020/pull/3#issuecomment-650359435>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AM6INWWXOS3ERZ3U6X7QCKLRYTZYBANCNFSM4OJTNAYQ>.

2020-06-26 19:39 UTC, andrewm898 commented
@googlebot

2020-06-26 19:41 UTC, andrewm898 commented
@googlebot

2020-06-26 19:46 UTC, andrewm898 commented
@googlebot

2020-06-26 19:48 UTC, andrewm898 commented
@googlebot I fixed it.

2020-06-26 19:54 UTC, andrewm898 commented
@googlebot

2020-06-26 20:36 UTC, andrewm898 commented
This branch has been rebased with the previous PR branch

2020-06-26 22:29 UTC, jnnybk commented on src/main/webapp/registration.html
> +    <form action="/add-organization" method="POST">
Let's try to have consistent indentation!

2020-06-26 22:29 UTC, jnnybk approved these changes

2020-06-29 14:04 UTC, Sarah-Addo commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
> +    String hourOpen = request.getParameter("hour-open");
maybe hoursOpen?

2020-06-29 14:04 UTC, Sarah-Addo commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
> +    String hourClosed = request.getParameter("hour-closed");
same here

2020-06-29 14:04 UTC, Sarah-Addo commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
> +    openHours.add(Integer.parseInt(hourOpen));
what format would the user have to input for this to work? i.e 9:30 pm or 21:30 etc

2020-06-29 14:04 UTC, Sarah-Addo commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
>  }
new line

2020-06-29 14:04 UTC, Sarah-Addo commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
> +    changeHistory.add("Organization was registered");
Do we not want the creation timestamp not apart of change history?

2020-06-29 14:04 UTC, Sarah-Addo commented on src/main/webapp/index.html
> +</html>
new line

2020-06-29 14:06 UTC, andrewm898 commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
> +    String hourOpen = request.getParameter("hour-open");
hourOpen refers to the hour of the day that the org opens, and hourClosed refers to the hour it closes

2020-06-29 14:07 UTC, andrewm898 commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
> +    openHours.add(Integer.parseInt(hourOpen));
for the prototype I left it as just using hours of the day with no minutes, I figured we can make this part more detailed in the future

2020-06-29 14:10 UTC, andrewm898 commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
> +    changeHistory.add("Organization was registered");
I figured we can change it to include that in a future PR when this is done with the history object instead of the string

2020-06-29 14:11 UTC, andrewm898 commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
> +    openHours.add(Integer.parseInt(hourOpen));
for the prototype, I left it as just using hours of the day with no minutes, I figured we can make this part more detailed in the future

2020-06-29 14:21 UTC, andrewm898 commented
I reverted this change ^ because git added a bunch of target files that didn't need to be added. This branch is ready to merge now

2020-06-29 17:43 UTC, Sarah-Addo approved these changes

2020-06-29 19:24 UTC, belraquib requested changes

2020-06-29 19:24 UTC, belraquib commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
> +    openHours.add(Integer.parseInt(hourOpen));
SG - but leave a TODO here with a link to the issue

2020-06-29 19:24 UTC, belraquib commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
> +    ArrayList<Integer> openHours = new ArrayList<Integer>();
can you leave a comment about what hour 0 means? is 12:00 AM ? or 1 AM?

2020-06-29 19:24 UTC, belraquib commented on src/main/java/com/google/sps/servlets/AddOrganizationServlet.java
> +    changeHistory.add("Organization was registered");
Leave a TODO

2020-06-29 19:24 UTC, belraquib commented on src/main/webapp/index_script.js
> +  organizationElement.addEventListener('click', () => {
remove since it doesn't do anything yet?

2020-06-29 19:56 UTC, belraquib requested changes

2020-06-29 19:56 UTC, belraquib commented on src/main/webapp/registration.html
> +      <input id = "hour-open" type = "text" pattern = "[0-23]{1}" name = "hour-open" placeholder="hour you open (0-23)"></input>
No `</input>`

2020-06-29 19:57 UTC, belraquib requested changes

2020-06-29 19:57 UTC, belraquib commented on src/main/webapp/registration.html
> +      <input id = "hour-open" type = "text" pattern = "[0-23]{1}" name = "hour-open" placeholder="hour you open (0-23)"></input>
this regex looks off to me

2020-06-29 20:31 UTC, merged